# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Homepage of Altuğ Yalçıntaş
email: altug.yalcintas@politics.ankara.edu.tr
description: >- # this means to ignore newlines until "baseurl:"
  Homepage of Altuğ Yalçıntaş. Altuğ Yalçıntaş is a computational social scientist and independent singer and songwriter. He is a professor at Ankara University.
  In his research Altuğ Yalçıntaş focuses on the applications of artificial intelligence in scientific knowledge production and humanities research.
twitter_username: EconResEthics
github_username: sekerefe
minimal_mistakes_skin: default 
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 1 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Altuğ Yalçıntaş"
  avatar : "/assets/images/photoAl2.jpg"
  bio    : "Computational social scientist and independent singer and songwriter"
  links:
    - label: "Academic Bio"
      icon: "fa-solid fa-graduation-cap"
      url: "https://drive.google.com/file/d/15kZZihvc5HzfaaUzlB0GwBgNBIdYOZkJ/view?pli=1"
    - label: "ORCID"
      icon: "fa-brands fa-orcid"
      url: "https://orcid.org/0000-0002-3344-0497"
    - label: "Research Gate"
      icon: "fa-brands fa-researchgate"
      url: "https://www.researchgate.net/profile/Altug-Yalcintas"
    - label: "Google Scholar"
      icon: "fa-brands fa-google-scholar"
      url: "https://scholar.google.com/citations?user=nmvLLJ8AAAAJ&hl=en"
    - label: "GitHub"
      icon: "fa-brands fa-github"
      url: "https://sekerefe.github.io"
    - label: "Tableau Public"
      icon: "fa-brands fa-tableau"
      url: "https://public.tableau.com/app/profile/altug.yalcintas"
    - label: "LinkedIn"
      icon: "fa-brands fa-linkedin-in"
      url: "https://www.linkedin.com/in/ayalcintas/"
    - label: "Twitter"
      icon: "fa-brands fa-x-twitter"
      url: "https://x.com/EconResEthics"
    - label: "Instagram"
      icon: "fa-brands fa-instagram"
      url: "https://www.instagram.com/altug.yalcintas/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:altug.yalcintas@politics.ankara.edu.tr"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
